<a href="https://colab.research.google.com/github/GinaMCV/S10.01.-APIS-REST/blob/main/S10_01_APIS_REST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importacion de librerias

In [21]:
import requests
import pandas as pd

# Nivel 1
Desde un Jupyter Notebook realizarás los siguientes ejercicios utilizando la librería requests de Python.
Exploración básica con una API de laboratorio.

Recursos:
- [{JSON} Placeholder](https://jsonplaceholder.typicode.com)

In [22]:
BASE_URL = "https://jsonplaceholder.typicode.com"

## 1. Consulta la API pública JSONPlaceholder utilizando el método GET para obtener:
- Lista de publicaciones (/posts)
- Lista de usuarios (/users)
- Lista de tareas (/todos)

## 2. Muestra por pantalla:

- La cantidad total de cada recurso.
- El código de estado de cada petición.

In [23]:
datos = {}
for recurso in ["posts", "users", "todos"]:
    resp = requests.get(f"{BASE_URL}/{recurso}", timeout=10)
    datos[recurso] = resp.json()
    print(f"/{recurso:<6} -> código de estado: {resp.status_code} | total de registros: {len(datos[recurso])}")

/posts  -> código de estado: 200 | total de registros: 100
/users  -> código de estado: 200 | total de registros: 10
/todos  -> código de estado: 200 | total de registros: 200

## 3. Realiza una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.

In [24]:
resp = requests.get(f"{BASE_URL}/posts/101", timeout=10)
print("Código de estado:", resp.status_code)

Código de estado: 404

## 4. Realiza una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.

- Muestra la respuesta JSON.
- Muestra el código de estado.

In [25]:
nueva_publicacion = {
    "title": "Publicacion de prueba",
    "body": "Este es el contenido de una publicación creada con como prueba.",
    "userId": 1,
}

resp = requests.post(f"{BASE_URL}/posts", json=nueva_publicacion, timeout=10)
print("Código de estado:", resp.status_code)
print("Respuesta JSON:")
print(resp.json())

Código de estado: 201
Respuesta JSON:
{'title': 'Publicacion de prueba', 'body': 'Este es el contenido de una publicación creada con como prueba.', 'userId': 1, 'id': 101}

## 5. Realiza una petición PATCH para modificar parcialmente una publicación existente.

- Muestra la respuesta JSON.
- Muestra el código de estado.

In [26]:
cambios = {"title": "Nuevo título modificado"}

resp = requests.patch(f"{BASE_URL}/posts/1", json=cambios, timeout=10)
print("Código de estado:", resp.status_code)
print("Respuesta JSON:")
print(resp.json())

Código de estado: 200
Respuesta JSON:
{'userId': 1, 'id': 1, 'title': 'Nuevo título modificado', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

## 6. Haz una petición DELETE sobre una publicación.

- Muestra la respuesta JSON.
- Muestra el código de estado.

In [27]:
resp = requests.delete(f"{BASE_URL}/posts/1", timeout=10)
print("Código de estado:", resp.status_code)
print("Respuesta JSON:", resp.json())

Código de estado: 200
Respuesta JSON: {}

# Nivel 2
Interacción con una API pública real

Recursos:
- [Try Public APIs for free](https://github.com/public-apis/public-apis)

## 1. Explora el repositorio de Public APIs y elige una API que permita realizar peticiones GET.

- API elegida: Studio Ghibli API
- URL base: https://ghibliapi.vercel.app

## 2. Lee la documentación de la API:

- Revisa la sección de endpoints disponibles. En un markdown, apunta al menos dos endpoints diferentes.
- Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anótalos.
- Verifica que la respuesta sea en formato JSON (es lo más adecuado para este ejercicio).

- **Endpoints**
  - GET /films: Lista de todas las películas
  - GET /films/{id}: Una película por su ID (UUID)
  - GET /people: Lista de personajes
  - GET /locations: Lista de localizaciones

- **Filtros / parámetros opcionales**
  - Algunas versiones de la API admiten `?limit=N` (limitar resultados) y `?fields=campo1,campo2`
  - El filtrado interesante (por director, por `rt_score`, por año)
  - Se puede navegar entre recursos: cada película incluye URLs de `people`, `species`, `locations` y `vehicles`.

- **Formato de respuesta**
  - JSON

## 3. Haz una petición GET sencilla:

- Muestra el código de estado de la respuesta.
- Imprime de forma clara algunos de los campos de la respuesta JSON.

In [28]:
BASE = "https://ghibliapi.vercel.app"

resp = requests.get(f"{BASE}/films", timeout=10)
print("Código de estado:", resp.status_code)
print("Content-Type:", resp.headers.get("Content-Type"))

films = resp.json()
print("Número de películas:", len(films))
print("Campos disponibles:", list(films[0].keys()))

print("\nAlgunas películas:")
for f in films[:5]:
    print(f"- {f['title']} ({f['release_date']}) | Director: {f['director']} | RT score: {f['rt_score']}")

Código de estado: 200
Content-Type: application/json; charset=utf-8
Número de películas: 22
Campos disponibles: ['id', 'title', 'original_title', 'original_title_romanised', 'image', 'movie_banner', 'description', 'director', 'producer', 'release_date', 'running_time', 'rt_score', 'people', 'species', 'locations', 'vehicles', 'url']

Algunas películas:
- Castle in the Sky (1986) | Director: Hayao Miyazaki | RT score: 95
- Grave of the Fireflies (1988) | Director: Isao Takahata | RT score: 97
- My Neighbor Totoro (1988) | Director: Hayao Miyazaki | RT score: 93
- Kiki's Delivery Service (1989) | Director: Hayao Miyazaki | RT score: 96
- Only Yesterday (1991) | Director: Isao Takahata | RT score: 100

## 4. Convierte los datos a un DataFrame de pandas:

Muestra las primeras filas de DataFrame.

In [29]:
df_films = pd.DataFrame(films)

for col in ["release_date", "running_time", "rt_score"]:
    df_films[col] = pd.to_numeric(df_films[col])

df_films[["title", "director", "release_date", "running_time", "rt_score"]].head()

,title,director,release_date,running_time,rt_score
0,Castle in the Sky,Hayao Miyazaki,1986,124,95
1,Grave of the Fireflies,Isao Takahata,1988,89,97
2,My Neighbor Totoro,Hayao Miyazaki,1988,86,93
3,Kiki's Delivery Service,Hayao Miyazaki,1989,102,96
4,Only Yesterday,Isao Takahata,1991,118,100

# Nivel 3
API de Open Data Barcelona

Recursos:

- [Open Data BCN](https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS)

## 1. Utiliza la API de Open Data BCN para:

Buscar un dataset de tu interés mediante package_search y package_show. .

In [30]:
CKAN_URL = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"

QUERY = "bicing"

resp = requests.get(f"{CKAN_URL}/package_search", params={"q": QUERY, "rows": 10}, timeout=20)
print("Código de estado:", resp.status_code)

resultado = resp.json()["result"]
print(f"Datasets encontrados: {resultado['count']}\n")

for pkg in resultado["results"]:
    formatos = sorted({r["format"] for r in pkg["resources"]})
    print(f"- {pkg['name']:<45} formatos: {formatos}")

Código de estado: 200
Datasets encontrados: 5

- estat-estacions-bicing                        formatos: ['JSON', 'application/x-7z-compressed']
- informacio-estacions-bicing                   formatos: ['JSON', 'application/x-7z-compressed']
- us-del-servei-bicing                          formatos: ['CSV', 'application/x-7z-compressed']
- cataleg-fotografies-elements-urbans-bcnroc    formatos: ['CSV', 'XML']
- bicing                                        formatos: ['CSV', 'application/x-7z-compressed']

## 2. De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON.

In [31]:
dataset_elegido, recurso_elegido = None, None

for pkg in resultado["results"]:
    for r in pkg["resources"]:
        if r["format"].upper() in ("CSV", "JSON") and r.get("datastore_active"):
            dataset_elegido, recurso_elegido = pkg["name"], r
            break
    if recurso_elegido:
        break

if recurso_elegido is None:
    raise ValueError("Ningún resultado tiene un recurso CSV/JSON con datastore activo. Prueba otra búsqueda (QUERY).")


resp = requests.get(f"{CKAN_URL}/package_show", params={"id": dataset_elegido}, timeout=20)
detalle = resp.json()["result"]

print("Dataset:", detalle["title"])
print("Recursos disponibles:")
for r in detalle["resources"]:
    print(f"  - {r['name'][:50]:<50} {r['format']:<5} datastore_active={r.get('datastore_active')}  id={r['id']}")

resource_id = recurso_elegido["id"]
print("\nRecurso seleccionado:", recurso_elegido["name"], "->", resource_id)

Dataset: Bicing service use of the city of Barcelona from August 2018 to March 2019
Recursos disponibles:
  - 2019_01_Gener_BICING_US.csv                        CSV   datastore_active=True  id=453abff9-fb75-4f31-a699-23509bf0eca2
  - 2019_01_Gener_BICING_US.7z                         application/x-7z-compressed datastore_active=False  id=dfbd6ba7-3cbe-49f0-aa3c-ce96a3194cfc
  - 2019_02_Febrer_BICING_US.csv                       CSV   datastore_active=True  id=8cd14603-4a48-4425-9683-4ac5b94faea6
  - 2019_02_Febrer_BICING_US.7z                        application/x-7z-compressed datastore_active=False  id=c994f528-da65-47f6-a3e1-8667ea7ffe3e
  - 2019_03_Marc_BICING_US.csv                         CSV   datastore_active=True  id=fd15ed46-9b4b-4af9-a9bb-25daf62a7f0c
  - 2019_03_Marc_BICING_US.7z                          application/x-7z-compressed datastore_active=False  id=5b69aba7-296b-4ebe-954b-5604ba0c86e3
  - 2018_08_Agost_BICING_US.csv                        CSV   datastore_active=True  id=38c94f78-07a8-40d9-b7b5-d9a9574b8ae9
  - 2018_08_Agost_BICING_US.7z                         application/x-7z-compressed datastore_active=False  id=32b5819c-987d-47bb-8724-2eb2228957c9
  - 2018_09_Setembre_BICING_US.csv                     CSV   datastore_active=True  id=727981d3-3038-4aa7-81b4-b47a35f99f37
  - 2018_09_Setembre_BICING_US.7z                      application/x-7z-compressed datastore_active=False  id=7b116c3c-4442-41d8-b4f1-0311a95a38d9
  - 2018_10_Octubre_BICING_US.csv                      CSV   datastore_active=True  id=9c507837-598a-4433-b027-a9aa5138f1f7
  - 2018_10_Octubre_BICING_US.7z                       application/x-7z-compressed datastore_active=False  id=f990113e-b362-478a-9d8c-53ad26c059fb
  - 2018_11_Novembre_BICING_US.csv                     CSV   datastore_active=True  id=6d35ca24-03f3-4a7c-b3fc-d46df3280302
  - 2018_11_Novembre_BICING_US.7z                      application/x-7z-compressed datastore_active=False  id=51302366-b8d2-485c-ac3d-32f983365a4a
  - 2018_12_Desembre_BICING_US.csv                     CSV   datastore_active=True  id=fc52c8b5-23bd-493e-8f47-a0da50983b0f
  - 2018_12_Desembre_BICING_US.7z                      application/x-7z-compressed datastore_active=False  id=4c22bc8a-81ef-404b-a3f6-7262bcac94b8

Recurso seleccionado: 2019_01_Gener_BICING_US.csv -> 453abff9-fb75-4f31-a699-23509bf0eca2

## 3. Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search por:

Recuperar al menos 100 registros.

In [32]:
resp = requests.get(
    f"{CKAN_URL}/datastore_search",
    params={"resource_id": resource_id, "limit": 100},
    timeout=30,
)
print("Código de estado:", resp.status_code)

res = resp.json()["result"]
registros = res["records"]
print("Registros totales en el recurso:", res.get("total"))
print("Registros recuperados:", len(registros))

Código de estado: 200
Registros totales en el recurso: 8055
Registros recuperados: 100

## 4. Convierte los resultados a un DataFrame.

In [33]:
df_bcn = pd.DataFrame(registros)
print(df_bcn.shape)
df_bcn.head()

(100, 6)

,electricalBikesInUsage,bikesInUsage,dateTime,mechanicalBikesInUsage,error,_id
0,0,50,2019-01-01T00:00:11,50,0,1
1,0,47,2019-01-01T00:05:12,47,0,2
2,0,50,2019-01-01T00:10:12,50,0,3
3,0,76,2019-01-01T00:15:12,76,0,4
4,0,119,2019-01-01T00:20:12,119,0,5

## 5. Guarda DataFrame en un archivo .csv.

In [34]:
df_bcn.to_csv("opendata_bcn.csv", index=False, encoding="utf-8")
print("Archivo guardado: opendata_bcn.csv")

pd.read_csv("opendata_bcn.csv").head()

Archivo guardado: opendata_bcn.csv

,electricalBikesInUsage,bikesInUsage,dateTime,mechanicalBikesInUsage,error,_id
0,0,50,2019-01-01T00:00:11,50,0,1
1,0,47,2019-01-01T00:05:12,47,0,2
2,0,50,2019-01-01T00:10:12,50,0,3
3,0,76,2019-01-01T00:15:12,76,0,4
4,0,119,2019-01-01T00:20:12,119,0,5